api = "0.10"

[extension]
id = "tech.atlantislab.extensions.graphql-hive"
version = "0.0.1"
name = "graphql-hive extension"
homepage = "https://github.com/atls/buildpacks"
description = "Installs graphql-hive on the runtime base image"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
